# degiro

In [27]:
import pandas as pd

## Data import

In [28]:
data = "../data/Account.csv"

In [29]:
df = pd.read_csv(data)

In [30]:
df.tail(10)

,Fecha,Hora,Fecha valor,Producto,ISIN,Descripción,Tipo,Variación,Unnamed: 8,Saldo,Unnamed: 10,ID Orden
779,27-07-2020,00:00,26-07-2020,MORGAN STANLEY EUR LIQUIDITY FUND,LU1959429272,Fondos del mercado monetario cambio de precio ...,NaN,EUR,"-0,02",EUR,"297,92",NaN
780,23-07-2020,00:00,22-07-2020,MORGAN STANLEY EUR LIQUIDITY FUND,LU1959429272,Fondos del mercado monetario cambio de precio ...,NaN,EUR,"-0,00",EUR,"297,93",NaN
781,22-07-2020,00:00,21-07-2020,MORGAN STANLEY EUR LIQUIDITY FUND,LU1959429272,Fondos del mercado monetario cambio de precio ...,NaN,EUR,"-0,00",EUR,"297,94",NaN
782,21-07-2020,00:00,20-07-2020,MORGAN STANLEY EUR LIQUIDITY FUND,LU1959429272,Fondos del mercado monetario cambio de precio ...,NaN,EUR,"-0,01",EUR,"297,94",NaN
783,20-07-2020,00:00,19-07-2020,MORGAN STANLEY EUR LIQUIDITY FUND,LU1959429272,Fondos del mercado monetario cambio de precio ...,NaN,EUR,"-0,01",EUR,"297,95",NaN
784,17-07-2020,00:00,16-07-2020,MORGAN STANLEY EUR LIQUIDITY FUND,LU1959429272,Fondos del mercado monetario cambio de precio ...,NaN,EUR,"-0,00",EUR,"297,96",NaN
785,16-07-2020,16:00,16-07-2020,MORGAN STANLEY EUR LIQUIDITY FUND,LU1959429272,Conversión fondos del mercado monetario: Compr...,NaN,NaN,NaN,EUR,"297,96",NaN
786,16-07-2020,16:00,16-07-2020,MORGAN STANLEY EUR LIQUIDITY FUND,LU1959429272,Conversión fondos del mercado monetario: Compr...,NaN,NaN,NaN,EUR,"250,00",NaN
787,16-07-2020,00:00,15-07-2020,MORGAN STANLEY EUR LIQUIDITY FUND,LU1959429272,Fondos del mercado monetario cambio de precio ...,NaN,EUR,"0,00",EUR,"250,00",NaN
788,15-07-2020,09:33,15-07-2020,NaN,NaN,Ingreso,NaN,EUR,"250,00",EUR,"250,00",NaN

### Cleaning

In [31]:
df.drop("ID Orden", axis=1, inplace=True) #drops col full of nans

In [32]:
df.dropna(subset=['Unnamed: 8'], inplace=True) #drops rows where no tax info can be extracted

In [33]:
df.rename(columns = {'Producto':'Name'}, inplace = True)

In [34]:
#df.head()
df[df["Descripción"].str.contains('PEY')]

,Fecha,Hora,Fecha valor,Name,ISIN,Descripción,Tipo,Variación,Unnamed: 8,Saldo,Unnamed: 10
204,20-06-2022,17:53,20-06-2022,PEYTO EXPL.+DEVEL.CORP.,CA7170461064,"Venta 200 PEYTO EXPL.+DEVEL.CORP.@9,5 EUR (CA7...",NaN,EUR,"1900,00",EUR,"3964,97"
362,30-09-2021,16:18,30-09-2021,PEYTO EXPL.+DEVEL.CORP.,CA7170461064,"Compra 200 PEYTO EXPL.+DEVEL.CORP.@6,5 EUR (CA...",NaN,EUR,"-1300,00",EUR,"281,69"

In [35]:
def split_string(string):
    if string.startswith('Compra') or string.startswith('Venta'):
        split_row = string.split("@")
        return pd.Series({
            'Action': split_row[0].split()[0],
            'Number': split_row[0].split()[1], #'Name': ' '.join(split_row[0].split()[2:]),
            'Price': split_row[1].split()[0].replace(',', '.'),
            'Currency': split_row[1].split()[1]
        })
    else:
        return pd.Series({
            'Action': None,
            'Number': None, #'Name': None,
            'Price': None,
            'Currency': None
        })

In [36]:
# Apply the function to each row of the dataframe
df[['Action', 'Number', 'Price', 'Currency']] = df['Descripción'].apply(split_string)

In [37]:
df['Action'].replace('Compra', 'buy', inplace=True)
df['Action'].replace('Venta', 'sell', inplace=True)

In [38]:
df['Date'] = pd.to_datetime(df['Fecha'] + ' ' + df['Hora'])

In [39]:
df['Date'] = pd.to_datetime(df['Fecha'] + ' ' + df['Hora'], format='%d-%m-%Y %H:%M')
df.drop(['Fecha', 'Hora', 'Fecha valor'], axis=1, inplace=True)

In [40]:
df['Price'] = df['Price'].astype(float)
df['Number'] = df['Number'].astype(float)
df['Unnamed: 8'] = df['Unnamed: 8'].str.replace(',','.').astype(float)

In [41]:
df['FIFOSharesRem'] = df['Number']

In [42]:
df.head(10)

,Name,ISIN,Descripción,Tipo,Variación,Unnamed: 8,Saldo,Unnamed: 10,Action,Number,Price,Currency,Date,FIFOSharesRem
1,FLATEX EURO BANKACCOUNT,NLFLATEXACNT,Degiro Cash Sweep Transfer,NaN,EUR,-1.33,EUR,"24,23",None,NaN,NaN,None,2023-04-13 18:04:00,NaN
2,LINEA DIRECTA ASEGURADORA SA,ES0105546008,Dividendo,NaN,EUR,1.64,EUR,"25,56",None,NaN,NaN,None,2023-04-13 07:16:00,NaN
3,LINEA DIRECTA ASEGURADORA SA,ES0105546008,Retención del dividendo,NaN,EUR,-0.31,EUR,"23,92",None,NaN,NaN,None,2023-04-13 07:16:00,NaN
4,NaN,NaN,Flatex Interest Income,NaN,EUR,0.00,EUR,"24,23",None,NaN,NaN,None,2023-04-01 22:01:00,NaN
6,FLATEX EURO BANKACCOUNT,NLFLATEXACNT,Degiro Cash Sweep Transfer,NaN,EUR,588.70,EUR,"612,93",None,NaN,NaN,None,2023-02-24 16:19:00,NaN
7,NAGARRO SE,DE000A3H2200,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-4.90,EUR,"24,23",None,NaN,NaN,None,2023-02-24 09:49:00,NaN
8,NAGARRO SE,DE000A3H2200,"Compra 6 Nagarro SE@97,3 EUR (DE000A3H2200)",NaN,EUR,-583.80,EUR,"29,13",buy,6.0,97.3,EUR,2023-02-24 09:49:00,6.0
9,NaN,NaN,Processed Flatex Withdrawal,NaN,EUR,5000.00,EUR,"612,93",None,NaN,NaN,None,2023-02-03 14:01:00,NaN
10,NaN,NaN,flatex Withdrawal,NaN,EUR,-5000.00,EUR,"-4387,07",None,NaN,NaN,None,2023-02-03 14:01:00,NaN
12,FLATEX EURO BANKACCOUNT,NLFLATEXACNT,Degiro Cash Sweep Transfer,NaN,EUR,-1174.11,EUR,"-561,18",None,NaN,NaN,None,2023-02-03 11:52:00,NaN

In [43]:
# steps to continue cleaning... (for the moment, a method can be established in stocks taxes)

### Tax Computation

In [44]:
df[df["Name"] == "ALIBABA GROUP HOLDING"]

,Name,ISIN,Descripción,Tipo,Variación,Unnamed: 8,Saldo,Unnamed: 10,Action,Number,Price,Currency,Date,FIFOSharesRem
28,ALIBABA GROUP HOLDING,US01609W1027,Retirada Cambio de Divisa,"1,0890",USD,-450.20,USD,"0,00",None,NaN,NaN,None,2023-01-30 18:09:00,NaN
29,ALIBABA GROUP HOLDING,US01609W1027,Ingreso Cambio de Divisa,NaN,EUR,413.40,EUR,"1935,72",None,NaN,NaN,None,2023-01-30 18:09:00,NaN
30,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-1.00,EUR,"1522,32",None,NaN,NaN,None,2023-01-30 18:09:00,NaN
31,ALIBABA GROUP HOLDING,US01609W1027,"Venta 4 ALIBABA GROUP HOLDING@112,55 USD (US01...",NaN,USD,450.20,USD,"450,20",sell,4.0,112.550,USD,2023-01-30 18:09:00,4.0
44,ALIBABA GROUP HOLDING,US01609W1027,Ingreso Cambio de Divisa,"1,0721",USD,445.44,USD,"0,00",None,NaN,NaN,None,2023-01-09 17:39:00,NaN
45,ALIBABA GROUP HOLDING,US01609W1027,Retirada Cambio de Divisa,NaN,EUR,-415.48,EUR,"60,62",None,NaN,NaN,None,2023-01-09 17:39:00,NaN
46,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-1.00,EUR,"476,10",None,NaN,NaN,None,2023-01-09 17:39:00,NaN
47,ALIBABA GROUP HOLDING,US01609W1027,"Compra 4 ALIBABA GROUP HOLDING@111,36 USD (US0...",NaN,USD,-445.44,USD,"-445,44",buy,4.0,111.360,USD,2023-01-09 17:39:00,4.0
159,ALIBABA GROUP HOLDING,US01609W1027,Retirada Cambio de Divisa,"1,0063",USD,-1517.42,USD,"0,00",None,NaN,NaN,None,2022-08-19 17:26:00,NaN
160,ALIBABA GROUP HOLDING,US01609W1027,Ingreso Cambio de Divisa,NaN,EUR,1507.91,EUR,"3698,32",None,NaN,NaN,None,2022-08-19 17:26:00,NaN
161,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-0.50,EUR,"2190,41",None,NaN,NaN,None,2022-08-19 17:26:00,NaN
162,ALIBABA GROUP HOLDING,US01609W1027,"Venta 17 ALIBABA GROUP HOLDING@89,26 USD (US01...",NaN,USD,1517.42,USD,"1517,42",sell,17.0,89.260,USD,2022-08-19 17:26:00,17.0
226,ALIBABA GROUP HOLDING,US01609W1027,ADR/GDR Pass-Through Fee,NaN,USD,-0.19,USD,"-0,19",None,NaN,NaN,None,2022-05-25 11:51:00,NaN
370,ALIBABA GROUP HOLDING,US01609W1027,Ingreso Cambio de Divisa,"1,1711",USD,729.53,USD,"0,01",None,NaN,NaN,None,2021-09-24 18:23:00,NaN
371,ALIBABA GROUP HOLDING,US01609W1027,Retirada Cambio de Divisa,NaN,EUR,-622.93,EUR,"596,15",None,NaN,NaN,None,2021-09-24 18:23:00,NaN
372,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-0.02,EUR,"1219,08",None,NaN,NaN,None,2021-09-24 18:23:00,NaN
373,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-0.50,EUR,"1219,10",None,NaN,NaN,None,2021-09-24 18:23:00,NaN
374,ALIBABA GROUP HOLDING,US01609W1027,"Compra 5 ALIBABA GROUP HOLDING@145,905 USD (US...",NaN,USD,-729.52,USD,"-729,52",buy,5.0,145.905,USD,2021-09-24 18:23:00,5.0
424,ALIBABA GROUP HOLDING,US01609W1027,Ingreso Cambio de Divisa,"1,1784",USD,1141.74,USD,"0,00",None,NaN,NaN,None,2021-07-28 15:32:00,NaN
425,ALIBABA GROUP HOLDING,US01609W1027,Retirada Cambio de Divisa,NaN,EUR,-968.87,EUR,"3795,56",None,NaN,NaN,None,2021-07-28 15:32:00,NaN
426,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-0.02,EUR,"4764,43",None,NaN,NaN,None,2021-07-28 15:32:00,NaN
427,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-0.50,EUR,"4764,45",None,NaN,NaN,None,2021-07-28 15:32:00,NaN
428,ALIBABA GROUP HOLDING,US01609W1027,"Compra 6 ALIBABA GROUP HOLDING@190,29 USD (US0...",NaN,USD,-1141.74,USD,"-1141,74",buy,6.0,190.290,USD,2021-07-28 15:32:00,6.0
438,ALIBABA GROUP HOLDING,US01609W1027,ADR/GDR Pass-Through Fee,NaN,USD,-0.07,USD,"-0,07",None,NaN,NaN,None,2021-05-21 13:05:00,NaN
488,ALIBABA GROUP HOLDING,US01609W1027,Ingreso Cambio de Divisa,"1,2018",USD,232.48,USD,"0,00",None,NaN,NaN,None,2021-03-04 16:31:00,NaN
489,ALIBABA GROUP HOLDING,US01609W1027,Retirada Cambio de Divisa,NaN,EUR,-193.44,EUR,"1738,52",None,NaN,NaN,None,2021-03-04 16:31:00,NaN
490,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-0.50,EUR,"1931,96",None,NaN,NaN,None,2021-03-04 16:31:00,NaN
491,ALIBABA GROUP HOLDING,US01609W1027,"Compra 1 ALIBABA GROUP HOLDING@232,478 USD (US...",NaN,USD,-232.48,USD,"-232,48",buy,1.0,232.478,USD,2021-03-04 16:31:00,1.0
566,ALIBABA GROUP HOLDING,US01609W1027,Ingreso Cambio de Divisa,"1,2178",USD,449.84,USD,"0,00",None,NaN,NaN,None,2020-12-24 15:44:00,NaN
567,ALIBABA GROUP HOLDING,US01609W1027,Retirada Cambio de Divisa,NaN,EUR,-369.39,EUR,"104,18",None,NaN,NaN,None,2020-12-24 15:44:00,NaN
568,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-0.01,EUR,"473,57",None,NaN,NaN,None,2020-12-24 15:44:00,NaN
569,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-0.50,EUR,"473,58",None,NaN,NaN,None,2020-12-24 15:44:00,NaN
570,ALIBABA GROUP HOLDING,US01609W1027,"Compra 2 ALIBABA GROUP HOLDING@224,92 USD (US0...",NaN,USD,-449.84,USD,"-449,84",buy,2.0,224.920,USD,2020-12-24 15:44:00,2.0
742,ALIBABA GROUP HOLDING,US01609W1027,Ingreso Cambio de Divisa,"1,1760",USD,852.00,USD,"0,00",None,NaN,NaN,None,2020-08-27 16:11:00,NaN
743,ALIBABA GROUP HOLDING,US01609W1027,Retirada Cambio de Divisa,NaN,EUR,-724.48,EUR,"150,92",None,NaN,NaN,None,2020-08-27 16:11:00,NaN
744,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-0.50,EUR,"875,40",None,NaN,NaN,None,2020-08-27 16:11:00,NaN
745,ALIBABA GROUP HOLDING,US01609W1027,Costes de transacción y/o externos de DEGIRO,NaN,EUR,-0.01,EUR,"875,90",None,NaN,NaN,None,2020-08-27 16:11:00,NaN
746,ALIBABA GROUP HOLDING,US01609W1027,Compra 3 ALIBABA GROUP HOLDING@284 USD (US0160...,NaN,USD,-852.00,USD,"-852,00",buy,3.0,284.000,USD,2020-08-27 16:11:00,3.0

In [45]:
def compute_gains(df: pd.DataFrame, shares_held: dict, sell_row: pd.Series) -> float:
    """
    Computes the gains or losses for a sell transaction using the FIFO method.

    Args:
        df: A pandas DataFrame with columns "Name", "Action", "Date", "Number", and "Price".
        shares_held: A dictionary with the running totals of shares held.
        sell_row: A pandas Series representing the sell transaction.

    Returns:
        The gains or losses for the transaction as a float.
    """
    shares_bought_list = []
    shares_sold = sell_row['Number']
    sale_price = sell_row['Price']
    gains = 0

    # Iterate over the shares held for the same stock in the order they were bought
    buy_rows = df.loc[(df['Name'] == sell_row['Name']) & (df['Action'] == 'buy') & (df['FIFOSharesRem']>0)].iterrows()
    costs_rows = df.loc[(df['Name'] == sell_row['Name']) & (df['Descripción'].str.contains('Coste'))]
    for i, buy_row in buy_rows:
        shares_bought = {}
        # If there are enough shares to cover the sale, calculate the gains/losses and update the shares held
        if buy_row['Number'] <= shares_sold :
            gains += (sale_price - buy_row['Price']) * buy_row['Number']
            shares_sold -= buy_row['Number']
            shares_held[buy_row['Name']] -= buy_row['Number']
            shares_bought['Number'] = buy_row['Number']
            shares_bought['Price'] = buy_row['Price']
            shares_bought_list.append(shares_bought)
            df.loc[i, 'FIFOSharesRem'] -= buy_row['Number']
            #locate additional costs 
            gains += costs_rows['Unnamed: 8'][costs_rows['Date'] == buy_row['Date']].sum()
            print('Buy costs: ', costs_rows['Unnamed: 8'][costs_rows['Date'] == buy_row['Date']].sum())
        # Otherwise, split the sale between the shares and break out of the loop
        else:
            gains += (sale_price - buy_row['Price']) * shares_sold
            shares_held[buy_row['Name']] -= shares_sold
            shares_bought['Number'] = shares_sold
            shares_bought['Price'] = buy_row['Price']
            shares_bought_list.append(shares_bought)
            gains += costs_rows['Unnamed: 8'][costs_rows['Date'] == buy_row['Date']].sum()
            print('Buy costs: ', costs_rows['Unnamed: 8'][costs_rows['Date'] == buy_row['Date']].sum())
            break
    
    gains += costs_rows['Unnamed: 8'][costs_rows['Date'] == sell_row['Date']].sum()
    print('Sell costs: ', costs_rows['Unnamed: 8'][costs_rows['Date'] == sell_row['Date']].sum())

    return gains, shares_bought_list, df

In [46]:
def calculate_returns(df: pd.DataFrame) -> float:
    """
    Calculates the total returns of a stock using the FIFO method.

    Args:
        df: A pandas DataFrame with columns "Name", "Action", "Date", "Number", and "Price".

    Returns:
        The total returns of the portfolio as a float.
    """
    # Sort the dataframe by date in ascending order
    df = df.sort_values('Date')

    # Create a dictionary to store the running totals of shares held
    shares_held = {}
    shares_sold = {}

    # Initialize the running totals to 0
    for name in df['Name'].unique():
        shares_held[name] = 0

    gains = {}
    boughts = {}
    # Iterate over the rows in the dataframe
    df_u = df.copy()
    for index, row in df.iterrows():
        # If the action is a sell, compute the gains/losses using the FIFO method
        if row['Action'] == 'sell':
            # Put if so that do consider 2-month period between seel and next buy
            g, gains['Shares Bought' + str(row['Date'])], df_u = compute_gains(df_u, shares_held, row)
            gains[row['Name'] + ' ' + str(row['Number']) + ' ' + str(row['Date'])] = g
            if (g<0): #& 
                #print(df[(df['ISIN'] == row['ISIN']) & (df['Action']=='buy') & (df['Date'] >= row['Date']) & (df['Date'] <= row['Date'] + pd.DateOffset(months=2))])
                df_empty = df[(df['ISIN'] == row['ISIN']) & (df['Action']=='buy') & (df['Date'] >= row['Date']) & (df['Date'] <= row['Date'] + pd.DateOffset(months=2))].empty
                if df_empty == False:
                    print('No se puede compensar pérdida por regla 2 meses')
                
            
            #print(df_u[~pd.isnull(df['FIFOSharesRem'])])
            

    return gains

In [47]:
df1 = df[df["Name"] == "PEYTO EXPL.+DEVEL.CORP."]

In [48]:
calculate_returns(df1)

Buy costs:  -8.67
Sell costs:  -4.4

{'Shares Bought2022-06-20 17:53:00': [{'Number': 200.0, 'Price': 6.5}],
 'PEYTO EXPL.+DEVEL.CORP. 200.0 2022-06-20 17:53:00': 586.9300000000001}

In [49]:
df1[(df1['Action'] == 'buy') | (df1['Action'] == 'sell')]

,Name,ISIN,Descripción,Tipo,Variación,Unnamed: 8,Saldo,Unnamed: 10,Action,Number,Price,Currency,Date,FIFOSharesRem
204,PEYTO EXPL.+DEVEL.CORP.,CA7170461064,"Venta 200 PEYTO EXPL.+DEVEL.CORP.@9,5 EUR (CA7...",NaN,EUR,1900.0,EUR,"3964,97",sell,200.0,9.5,EUR,2022-06-20 17:53:00,200.0
362,PEYTO EXPL.+DEVEL.CORP.,CA7170461064,"Compra 200 PEYTO EXPL.+DEVEL.CORP.@6,5 EUR (CA...",NaN,EUR,-1300.0,EUR,"281,69",buy,200.0,6.5,EUR,2021-09-30 16:18:00,200.0

In [50]:
df1['Number'].loc[362] = float(210)
df1['FIFOSharesRem'].loc[362] = float(210)

/var/folders/zf/p75y8jj52c72dh5cv6ys92pm0000gn/T/ipykernel_13905/3028729928.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Number'].loc[362] = float(210)
/var/folders/zf/p75y8jj52c72dh5cv6ys92pm0000gn/T/ipykernel_13905/3028729928.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['FIFOSharesRem'].loc[362] = float(210)

In [51]:
df1[(df1['Action'] == 'buy') | (df1['Action'] == 'sell')]

,Name,ISIN,Descripción,Tipo,Variación,Unnamed: 8,Saldo,Unnamed: 10,Action,Number,Price,Currency,Date,FIFOSharesRem
204,PEYTO EXPL.+DEVEL.CORP.,CA7170461064,"Venta 200 PEYTO EXPL.+DEVEL.CORP.@9,5 EUR (CA7...",NaN,EUR,1900.0,EUR,"3964,97",sell,200.0,9.5,EUR,2022-06-20 17:53:00,200.0
362,PEYTO EXPL.+DEVEL.CORP.,CA7170461064,"Compra 200 PEYTO EXPL.+DEVEL.CORP.@6,5 EUR (CA...",NaN,EUR,-1300.0,EUR,"281,69",buy,210.0,6.5,EUR,2021-09-30 16:18:00,210.0

In [52]:
calculate_returns(df1)

Buy costs:  -8.67
Sell costs:  -4.4

{'Shares Bought2022-06-20 17:53:00': [{'Number': 200.0, 'Price': 6.5}],
 'PEYTO EXPL.+DEVEL.CORP. 200.0 2022-06-20 17:53:00': 586.9300000000001}

In [53]:
calculate_returns(df)

Buy costs:  -0.5700000000000001
Sell costs:  -0.5700000000000001
Buy costs:  -0.5
Sell costs:  -0.5
Buy costs:  -0.58
Sell costs:  -0.59
Buy costs:  -0.5
Sell costs:  -0.5
Buy costs:  -4.14
Sell costs:  -4.13
Buy costs:  -0.52
Buy costs:  -0.5
Sell costs:  -0.52
Buy costs:  -0.58
Sell costs:  -0.58
Buy costs:  -2.08
Sell costs:  -2.07
Buy costs:  -0.51
Sell costs:  -0.51
Buy costs:  -0.51
Sell costs:  -0.51
Buy costs:  -0.5
Buy costs:  -0.5
Sell costs:  -0.5
Buy costs:  -0.51
Sell costs:  -0.51
Buy costs:  -0.5
Sell costs:  -0.5
Buy costs:  -0.5700000000000001
Sell costs:  -0.56
Buy costs:  -0.5700000000000001
Sell costs:  -0.56
Buy costs:  -0.5700000000000001
Buy costs:  -0.58
Sell costs:  -0.58
Buy costs:  -4.28
Buy costs:  -4.24
Buy costs:  -4.29
Buy costs:  -4.26
Sell costs:  -5.86
Buy costs:  -4.26
Buy costs:  -4.24
Sell costs:  -4.54
Buy costs:  -0.52
Buy costs:  -0.52
Sell costs:  -0.54
Buy costs:  -2.08
Sell costs:  0.0
Buy costs:  -2.08
Sell costs:  -2.08
Buy costs:  -2.1
Buy costs:  0.0
Sell costs:  0.0
Buy costs:  -4.34
Sell costs:  -4.4
Buy costs:  -8.67
Sell costs:  -4.4
Buy costs:  -0.5700000000000001
Buy costs:  -0.53
Buy costs:  -0.64
Sell costs:  -0.5
Buy costs:  -0.5
Sell costs:  -0.5
Buy costs:  -4.57
Buy costs:  -4.4
Sell costs:  -4.4
No se puede compensar pérdida por regla 2 meses
Buy costs:  -0.51
Buy costs:  -0.51
Buy costs:  -0.5
Buy costs:  -0.52
Buy costs:  -0.52
Buy costs:  -1.0
Sell costs:  -0.5
Buy costs:  -4.4
Buy costs:  -4.4
Sell costs:  -4.4
No se puede compensar pérdida por regla 2 meses
Buy costs:  -0.52
Buy costs:  -0.52
Sell costs:  -0.5
Buy costs:  -0.52
Buy costs:  -0.52
Buy costs:  -0.53
Sell costs:  -1.0
Buy costs:  -4.01
Buy costs:  -4.61
Sell costs:  -4.9
Buy costs:  -0.5
Sell costs:  -1.0
Buy costs:  -4.9
Sell costs:  -4.9
Buy costs:  -1.0
Sell costs:  -1.0
Buy costs:  -4.4
Buy costs:  -4.4
Buy costs:  -4.4
Buy costs:  -4.9
Sell costs:  -4.9
Sell costs:  -1.0
Sell costs:  -1.0

{'Shares Bought2020-08-24 19:07:00': [{'Number': 21.0, 'Price': 13.75}],
 'CARNIVAL CORPORATION C 21.0 2020-08-24 19:07:00': 44.43,
 'Shares Bought2020-09-03 19:25:00': [{'Number': 1.0, 'Price': 145.84}],
 'BIGCOMMERCE HOLDINGS-SER 1 1.0 2020-09-03 19:25:00': -48.84,
 'Shares Bought2020-09-21 15:30:00': [{'Number': 25.0, 'Price': 4.45}],
 'ARMSTRONG FLOORING INC-W/I 25.0 2020-09-21 15:30:00': -4.170000000000003,
 'Shares Bought2020-09-29 20:01:00': [{'Number': 1.0, 'Price': 84.0}],
 'PELOTON INTERACTIVE INC-A 1.0 2020-09-29 20:01:00': 17.200000000000003,
 'Shares Bought2020-10-27 12:21:00': [{'Number': 15.0, 'Price': 18.5}],
 'KOJAMO OYJ 15.0 2020-10-27 12:21:00': -21.16999999999999,
 'Shares Bought2020-11-02 17:16:00': [{'Number': 5.0, 'Price': 32.63},
  {'Number': 0.0, 'Price': 12.39}],
 'FARFETCH LTD-CLASS A 5.0 2020-11-02 17:16:00': -1.6900000000000057,
 'Shares Bought2020-11-17 15:40:00': [{'Number': 25.0, 'Price': 28.9}],
 'BARRICK GOLD CORPORATI 25.0 2020-11-17 15:40:00': -82.90999999999998,
 'Shares Bought2020-12-07 12:19:00': [{'Number': 2.0, 'Price': 81.7}],
 'PHARMA MAR SA 2.0 2020-12-07 12:19:00': -30.45000000000001,
 'Shares Bought2021-02-04 21:25:00': [{'Number': 2.0, 'Price': 49.775}],
 'INTEL CORPORATION - CO 2.0 2021-02-04 21:25:00': 16.169999999999995,
 'Shares Bought2021-02-04 21:26:00': [{'Number': 3.0, 'Price': 34.86}],
 'CORE LABORATORIES N.V. 3.0 2021-02-04 21:26:00': 1.4699999999999949,
 'Shares Bought2021-02-16 20:59:00': [{'Number': 1.0, 'Price': 183.0},
  {'Number': 0.0, 'Price': 166.9777}],
 'BOEING COMPANY (THE) C 1.0 2021-02-16 20:59:00': 31.659999999999997,
 'Shares Bought2021-02-24 16:59:00': [{'Number': 3.0, 'Price': 50.3}],
 'UBER TECHNOLOGIES INC. COMMON STOCK 3.0 2021-02-24 16:59:00': 10.410000000000007,
 'Shares Bought2021-03-01 16:21:00': [{'Number': 1.0, 'Price': 198.0}],
 'TELADOC INC. COMMON S 1.0 2021-03-01 16:21:00': 29.0,
 'Shares Bought2021-03-03 21:30:00': [{'Number': 10.0, 'Price': 8.4}],
 'CALLON PETROLEUM CO 10.0 2021-03-03 21:30:00': 233.37000000000003,
 'Shares Bought2021-03-05 16:17:00': [{'Number': 20.0, 'Price': 8.4},
  {'Number': 5.0, 'Price': 32.96}],
 'CALLON PETROLEUM CO 25.0 2021-03-05 16:17:00': 590.4699999999999,
 'Shares Bought2021-07-28 09:25:00': [{'Number': 22.0, 'Price': 25.45},
  {'Number': 19.0, 'Price': 25.25},
  {'Number': 20.0, 'Price': 28.65},
  {'Number': 19.0, 'Price': 23.4}],
 'AKKA TECHNOLOGIES 80.0 2021-07-28 09:25:00': 1639.8200000000002,
 'Shares Bought2021-08-25 11:30:00': [{'Number': 22.0, 'Price': 23.4},
  {'Number': 1.0, 'Price': 23.88}],
 'AKKA TECHNOLOGIES 23.0 2021-08-25 11:30:00': 528.3600000000001,
 'Shares Bought2021-09-30 16:13:00': [{'Number': 6.0, 'Price': 104.17},
  {'Number': 7.0, 'Price': 92.09}],
 'HOWARD HUGHES CORPORAT 13.0 2021-09-30 16:13:00': -127.62000000000005,
 'Shares Bought2021-11-09 16:36:00': [{'Number': 15.0, 'Price': 8.005}],
 'ISHARES AUTOMATION & ROBOTICS UCITS E... 15.0 2021-11-09 16:36:00': 67.86499999999998,
 'Shares Bought2021-11-09 16:37:00': [{'Number': 20.0, 'Price': 8.005}],
 'ISHARES AUTOMATION & ROBOTICS UCITS E... 20.0 2021-11-09 16:37:00': 88.98,
 'Shares Bought2021-11-09 16:38:00': [{'Number': 25.0, 'Price': 13.066},
  {'Number': 90.0, 'Price': 12.736}],
 'ISHARES GOLD PRODUCERS UCITS ETF USD ... 115.0 2021-11-09 16:38:00': -37.720000000000155,
 'Shares Bought2022-05-09 09:17:00': [{'Number': 75.0, 'Price': 9.0}],
 'UMANIS 75.0 2022-05-09 09:17:00': 580.76,
 'Shares Bought2022-06-20 17:53:00': [{'Number': 200.0, 'Price': 6.5}],
 'PEYTO EXPL.+DEVEL.CORP. 200.0 2022-06-20 17:53:00': 586.9300000000001,
 'Shares Bought2022-08-04 20:20:00': [{'Number': 20.0, 'Price': 15.45},
  {'Number': 8.0, 'Price': 12.2},
  {'Number': 40.0, 'Price': 15.72}],
 'SCIPLAY CORPORATION - CLASS A COMMON ... 68.0 2022-08-04 20:20:00': -180.0784,
 'Shares Bought2022-08-04 20:23:00': [{'Number': 2.0, 'Price': 166.9777}],
 'BOEING COMPANY (THE) C 2.0 2022-08-04 20:23:00': -0.9528000000000247,
 'Shares Bought2022-08-19 09:07:00': [{'Number': 9.0, 'Price': 127.0},
  {'Number': 8.0, 'Price': 148.0}],
 'NAGARRO SE 17.0 2022-08-19 09:07:00': -296.9699999999999,
 'Shares Bought2022-08-19 17:26:00': [{'Number': 3.0, 'Price': 284.0},
  {'Number': 2.0, 'Price': 224.92},
  {'Number': 1.0, 'Price': 232.478},
  {'Number': 6.0, 'Price': 190.29},
  {'Number': 5.0, 'Price': 145.905},
  {'Number': 0.0, 'Price': 111.36}],
 'ALIBABA GROUP HOLDING 17.0 2022-08-19 17:26:00': -1892.223,
 'Shares Bought2022-08-29 09:54:00': [{'Number': 10.0, 'Price': 148.0},
  {'Number': 2.0, 'Price': 130.0}],
 'NAGARRO SE 12.0 2022-08-29 09:54:00': -452.39999999999986,
 'Shares Bought2022-08-30 18:18:00': [{'Number': 7.0, 'Price': 70.08},
  {'Number': 7.0, 'Price': 65.85}],
 'JD.COM INC. - AMERICA 14.0 2022-08-30 18:18:00': -96.87999999999992,
 'Shares Bought2022-09-13 19:47:00': [{'Number': 2.0, 'Price': 67.21},
  {'Number': 2.0, 'Price': 67.21},
  {'Number': 8.0, 'Price': 91.14}],
 'NOVO NORDISK A/S COMMO 12.0 2022-09-13 19:47:00': 282.5100000000001,
 'Shares Bought2022-09-22 09:00:00': [{'Number': 5.0, 'Price': 209.0},
  {'Number': 500.0, 'Price': 209.0}],
 'SCIENTIFIC D. 505.0 2022-09-22 09:00:00': -24758.52,
 'Shares Bought2022-12-07 18:36:00': [{'Number': 100.0, 'Price': 12.39}],
 'FARFETCH LTD-CLASS A 100.0 2022-12-07 18:36:00': -771.0,
 'Shares Bought2023-01-30 09:04:00': [{'Number': 10.0, 'Price': 102.62}],
 'ADIDAS AG 10.0 2023-01-30 09:04:00': 431.5999999999999,
 'Shares Bought2023-01-30 18:09:00': [{'Number': 4.0, 'Price': 111.36}],
 'ALIBABA GROUP HOLDING 4.0 2023-01-30 18:09:00': 2.759999999999991,
 'Shares Bought2023-01-31 09:21:00': [{'Number': 4.0, 'Price': 130.0},
  {'Number': 5.0, 'Price': 118.0},
  {'Number': 10.0, 'Price': 94.7},
  {'Number': 1.0, 'Price': 97.3}],
 'NAGARRO SE 20.0 2023-01-31 09:21:00': 330.70000000000016,
 'Shares Bought2023-02-02 17:28:00': [],
 'BROOKFIELD CORPORATION INC CLASS A 28.0 2023-02-02 17:28:00': -1.0,
 'BROOKFIELD ASSET MANAGEMENT LTD CLASS A 7.0 2023-02-02 17:28:00': -1.0}